# Generated by Django 4.2.3 on 2023-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.URLField(verbose_name='Odkaz na obrazek')),
                ('nazev', models.CharField(blank=True, max_length=100, verbose_name='Nazev')),
            ],
        ),
    ]
