# Generated by Django 4.2.3 on 2023-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_nazev_remove_image_obrazek_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_defined_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
