# Generated by Django 4.2.3 on 2023-07-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_user_defined_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user_defined_id',
        ),
    ]
