# Generated by Django 4.2.3 on 2023-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_user_defined_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_defined_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
