# Generated by Django 4.2.3 on 2023-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_user_defined_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_url',
            field=models.URLField(),
        ),
    ]
