# Generated by Django 4.2.3 on 2023-07-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user_defined_id',
        ),
    ]
