# Generated by Django 4.2.3 on 2023-07-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=100, verbose_name='Nazev')),
                ('kod', models.CharField(blank=True, max_length=100, verbose_name='Kod')),
                ('zobrazit', models.BooleanField(blank=True, default=False, verbose_name='Zobrazit')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota', models.CharField(max_length=100, verbose_name='Hodnota')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.attributevalue')),
                ('nazev_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.attributename')),
            ],
        ),
    ]
