# Generated by Django 4.2.3 on 2023-07-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='nazev_atributu_id',
            new_name='nazev_atributu',
        ),
    ]
