# Generated by Django 4.2.3 on 2023-07-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_rename_nazev_atributu_id_attribute_nazev_atributu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='hodnota_atributu_id',
            new_name='hodnota_atributu',
        ),
    ]
