# Generated by Django 4.2.3 on 2023-07-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_rename_hodnota_atributu_id_attribute_hodnota_atributu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributename',
            old_name='kod',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='attributename',
            old_name='nazev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attributename',
            old_name='zobrazit',
            new_name='show',
        ),
    ]
