# Generated by Django 4.2.3 on 2023-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_rename_nazev_atributu_attribute_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributename',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='show',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
