# Generated by Django 4.2.3 on 2023-07-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0009_attribute_user_defined_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='attributename',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='user_defined_id',
        ),
    ]
