# Generated by Django 4.2.3 on 2023-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_user_defined_id_image__actual_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='_actual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(unique=True),
        ),
    ]
