# Generated by Django 4.2.3 on 2023-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_image__actual_id_alter_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='_actual_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
