# Generated by Django 4.2.3 on 2023-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_catalog_user_defined_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='_actual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='_actual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='_actual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='_actual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.IntegerField(unique=True),
        ),
    ]
