# Generated by Django 4.2.3 on 2023-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_catalog__actual_id_alter_catalog_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='_actual_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_actual_id',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='_actual_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='_actual_id',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
