# Generated by Django 4.2.3 on 2023-07-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Nazev')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Popis')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cena')),
                ('mena', models.CharField(choices=[('CZK', 'Czech Crown'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], max_length=3, verbose_name='Mena')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='Publikovano dne')),
                ('is_published', models.BooleanField(blank=True, default=False, verbose_name='Publikovano')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=100, verbose_name='Nazev')),
                ('obrazek_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=200, verbose_name='Nazev')),
                ('attributes_ids', models.ManyToManyField(to='attributes.attribute')),
                ('obrazek_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.image')),
                ('product_ids', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
