# Generated by Django 4.2.3 on 2023-07-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_obrazek_id_productimage_obrazek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='obrazek_id',
            new_name='obrazek',
        ),
    ]
