# Generated by Django 4.2.3 on 2023-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_rename_hodnota_atributu_id_attribute_hodnota_atributu'),
        ('products', '0005_rename_product_ids_catalog_products_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='attributes_ids',
            field=models.ManyToManyField(null=True, to='attributes.attribute'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='products_ids',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
