# Generated by Django 4.2.3 on 2023-07-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_catalog_user_defined_id_product_user_defined_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributes',
            options={'verbose_name_plural': 'product attributes'},
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='user_defined_id',
        ),
    ]
