# Generated by Django 4.2.3 on 2023-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productattributes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='user_defined_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='user_defined_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattributes',
            name='user_defined_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='user_defined_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
