# Generated by Django 4.2.3 on 2023-07-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='user_defined_id',
        ),
    ]
