# Generated by Django 4.2.3 on 2023-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0009_attribute_user_defined_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='attributename',
            name='user_defined_id',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='user_defined_id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='_actual_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='attributename',
            name='_actual_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='_actual_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
