# Generated by Django 4.2.3 on 2023-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0011_alter_attribute__actual_id_alter_attribute_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='_actual_id',
        ),
        migrations.RemoveField(
            model_name='attributename',
            name='_actual_id',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='_actual_id',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
